data:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: 'true'
  tty: true
  image: busybox
  volumes:
  - /srv/docker/tvserver:/var/lib/mysql
  stdin_open: true

db:
  image: mysql:v5.7
  environment:
    MYSQL_USERNAME: ${MYSQL_USERNAME}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    MYSQL_DATABASE: ${MYSQL_DATABASE}
    LOCATION: ${LOCATION}
    SECRET_KEY_TOKEN: ${SECRET_KEY_TOKEN}
  volumes_from:
    - data
  labels:
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: 'environment'

web:  
  image: registry.thealexauer.me:5000/tvserver:latest
  environment:
    MYSQL_USERNAME: ${MYSQL_USERNAME}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    MYSQL_DATABASE: ${MYSQL_DATABASE}
    LOCATION: ${LOCATION}
    SECRET_KEY_TOKEN: ${SECRET_KEY_TOKEN}
  volumes_from:
    - data
  labels:
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: 'environment'
